AdExNetwork/adex-validator

.travis.yml, package-lock.json, package.json, test/run-integration-tests.sh
=> Integration test final touch

services/validatorWorker/follower.js, services/validatorWorker/leader.js, services/validatorWorker/lib/followerRules.js, test/integration.js
Fixes #56 
it depends on the PR #55 being merged
=> Fix follower tick

services/validatorWorker/producer.js, test/integration.js
total balances sum should match the deposit
=> Fix exceed balance & test case

docs/validator-messages.md, services/validatorWorker/heartbeat.js
=> fix: add timestamp and timestampHash property

routes/channel.js, services/sentry/eventAggregator.js, services/validatorWorker/producer.js
optimizes event submission via caching a channel into the recorder itself
=> Optimization: events submission

docs/configuration.md, routes/schemas.js, test/fixtures.js
=> fix: numeric string

services/validatorWorker/lib/mergeAggrs.js
=> mergeAggrs: make it event generic

.prettierrc, bin/sentry.js, bin/validatorWorker.js, package-lock.json, package.json, services/lib.js, services/sentry/eventAggregator.js, services/validatorWorker/lib/sentryInterface.js, services/validatorWorker/producer.js
Change from `console.log` to logger
=> Change to  logger

bin/sentry.js, bin/validatorWorker.js, docs/api.md, routes/channel.js, routes/schemas.js, services/lib.js, services/sentry/eventAggregator.js, services/sentry/lib/eventReducer.js, services/validatorWorker/lib/sentryInterface.js, services/validatorWorker/producer.js, test/integration.js, test/lib.js, test/routes.js
=> update: logging, tests

services/validatorWorker/lib/fees.js, services/validatorWorker/lib/followerRules.js, test/index.js
fixed a pretty critical bug in `fees.js`
=> Math fixes

adapters/ethereum/index.js, package-lock.json, package.json
This allows the Ethereum adapter to allow authenticating as an Identity
This is needed when the channel is created by an Identity, in order to be able to close it
=> Authenticate with Identity

adapters/dummy/index.js, adapters/ethereum/index.js, adapters/lib.js, middlewares/channel.js, package-lock.json, package.json, routes/channel.js, routes/channelCreate.js, routes/schemas.js, test/fixtures.js, test/integration.js, test/lib.js, test/prep-db/mongo.js, test/routes.js
=> channelIfGrace

docs/fees.md
=> Document how the calculation of fees is made

test/routes.js
=> fix: weird test issues

services/sentry/eventAggregator.js, test/routes.js
=> Return Forbiden on channel close from invalid user

routes/channel.js, test/integration.js, test/lib.js, test/prep-db/mongo.js, test/routes.js
=> added event aggr & channel filter tests

adapters/lib.js, routes/channel.js, test/fixtures.js, test/run-integration-tests.sh, test/scripts/ethereum.sh
=> fix: total pages count negative

Dockerfile, README.md, docker-compose.yml
* docker-compose updated
* Dockerfile CMD changed to not launch validator AND sentry
=> Docker fixes

routes/channel.js
=> Event aggr fixes

adapters/lib.js
removing two things we don't need
=> No addrEq/watcher

services/sentry/eventAggregator.js, test/integration.js
fixes the health test race condition
=> eventAggregator: update created when immediately saving aggregates

routes/channel.js, scripts/prune.js, services/validatorWorker/follower.js, services/validatorWorker/heartbeat.js, services/validatorWorker/leader.js, services/validatorWorker/lib/followerRules.js, test/integration.js
=> prevent sending heartbeat on exhausted channels

docs/api.md, routes/channel.js, routes/schemas.js, services/sentry/lib/eventReducer.js, test/integration.js
=> update: eventTimeAggregates, privacy

routes/channel.js, routes/schemas.js, services/sentry/lib/eventReducer.js, test/integration.js, test/lib.js
=> 177 adslot arg

bin/validatorWorker.js, routes/channel.js, test/integration.js
=> should only return payouts & rename total

routes/channel.js, services/validatorWorker/lib/sentryInterface.js, test/integration.js
=> 167 last heartbeat

routes/schemas.js, services/sentry/lib/access.js, services/sentry/lib/eventReducer.js, test.js, test/integration.js, test/lib.js, test/routes.js
=> impression commission and pay event

bin/sentry.js, routes/volume.js, services/sentry/lib/access.js, test/integration.js, test/routes.js
Fixes #196 #194 #199 
Adds volume routes
=> 198 fix close pay

.well-known/dnt-policy.txt, nginx.conf
1 - https://www.eff.org/dnt-policy
=> Implement DNT policy as per EFF [1]

services/sentry/lib/eventReducer.js
=> Issue #222 Fix: pay event eventcount bignum toString

routes/schemas.js, services/validatorWorker/lib/fees.js
allowing you to override the address on which fees are received
=> Implement validator.feeAddr

README.md, routes/channel.js, routes/schemas.js, services/sentry/analyticsRecorder.js, services/sentry/eventAggregator.js, services/sentry/lib/eventReducer.js, services/sentry/lib/getPayout.js, test/index.js
See [AIP 23](https://github.com/AdExNetwork/aips/issues/23)
=> Analytics recorder (implement AIP 23)

docs/api.md, docs/configuration.md
=> Update api docs

adapters/ethereum/index.js, package.json, routes/analytics.js, services/sentry/analyticsRecorder.js, test/run-integration-tests.sh
A route to return the advanced reports
A few other minor things:
- data by country is now scoped by epoch
- using return/throw in a few places instead of `Promise.resolve`/`Promise.reject`
=> Analytics: advanced reports

package-lock.json, package.json, services/sentry/lib/access.js, test/integration.js
Implements further restrictions on the hostname from which you can send events
=> Restrictions

routes/analytics.js, test/integration.js, test/run-integration-tests.sh
=> Analytics test

services/sentry/analyticsRecorder.js
fixes `reportPublisherToCountryPay` record value
=> fix reportPublisherToCountryPay record

scripts/analyticsAggregator.js, test/analyticsAggregator.js
=> Analytics agg

services/sentry/analyticsRecorder.js
=> Advanced analytics: collect epoch-based ad slot stats

package-lock.json, package.json, routes/channel.js, services/sentry/lib/getPayout.js
adds adSlotType, userAgentOS, userAgentBrowserFamily
Solves #283
=> Set all the targeting variables 

services/sentry/analyticsRecorder.js
Add hourly channel -> adslot stats to the AIP 23 system
=> analyticsRecorder: add hour->channel->adslot

routes/analytics.js
=> analytics: better pipeline that uses decimal (128bit)

docs/configuration.md, docs/follower.md, services/validatorWorker/lib/followerRules.js
=> #35 Docs: getHealthPromilles

docs/api.md, routes/channel.js, routes/schemas.js, services/sentry/eventAggregator.js, services/validatorWorker/follower.js, services/validatorWorker/leader.js, services/validatorWorker/lib/followerRules.js, services/validatorWorker/lib/index.js, test/integration.js
=> stop accepting event on exhuasted channels

scripts/distribute-rewards.js
Currently, `distribute-rewards` does not take the slashes into consideration 
Take this example:
1. Two users open bonds sized 100 and 50 ADX
2. Pool is slashed 50% 
3. Another user adds a 50 ADX bond. At this stage, the effective values are 50, 25 (first bonds) and 50
- this is 40%, 20%, 40% - vs 50%/25%/25% as it would be calculated if slashes were not taken into account
This needs to be taken into consideration.
Before this PR it was not - which is not affecting anything since the current pool has no slashing. 
But for the future, slashing needs to be taken into account or otherwise the distribution is incorrect.
=> distribute-rewards: take slashes into consideration

.gitignore, services/sentry/lib/eventReducer.js, services/sentry/lib/getPayout.js, test/integration.js
* fixes close channel event - integration test and the actual event handle
=> Close channels fix

db.js, package-lock.json, package.json
Support TLS connections to the mongo server/replicaset & bump mongodb driver version
=> Support TLS connections to the mongo server/ replicasets

scripts/distribute-incentives.js, scripts/distribute-rewards.js
* adds `poolId` to rewards and incentives distribution channels - closes https://github.com/AdExNetwork/adex-validator/issues/328
* add rewards distribution stats
=> Rewards distribution stats update

routes/channel.js
Make page in /channel/list integer
=> fix: page type
